sudo: false

language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cppcheck
      - libgtest-dev

before_install:
  - pip install --user cpp-coveralls cpplint

script:
  - mkdir build
  - cd build
  - cmake ..
  - make all
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false